### ISSUE TITLE
Missing --service-name flag

### ISSUE THREAD

**Issue by RomanDvorsky** [kubecost/kubectl-cost#105]
I do have custom implementation of the kubecost analyzer in different namespace and with different name so I'm not able to call tui:

see:
![image](https://user-images.githubusercontent.com/36188474/166960717-b77b7296-9a89-498f-814a-26a87197568b.png)

or:
![image](https://user-images.githubusercontent.com/36188474/166960794-448f5939-2343-4437-a73c-c797c6bca4a7.png)

list of services:
![image](https://user-images.githubusercontent.com/36188474/166960952-47d7e8f2-8bef-4389-ba11-dbe7f815df96.png)

**Comment by michaelmdresser** [comment]
Hi @RomanDvorsky, v0.2.7 of `kubectl cost` was just released, which should resolve this issue. Let me know if it works for you!

**Comment by RomanDvorsky** [comment]
Cool! works fine thx!
