### ISSUE TITLE
[bug] kubectl-cost version returns blank output

### ISSUE THREAD

**Issue by kranurag7** [kubecost/kubectl-cost#111]
While executing the command `kubectl-cost version`, I'm getting blank output. 

```
$ kubectl-cost version
kubectl cost version info
    Git Commit:   
    Git Branch:   
    Git State:    
    Git Summary:  
    Build Date:
```
The command should return output with proper version and commit ID. 

gz#1988<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1988'>Zendesk ticket #1988</a>)</i>

**Comment by kranurag7** [comment]
This is happening when I'm building the binary locally, so it's not a bug I think. I think I should close the issue now. Sorry, from my side.

**Comment by michaelmdresser** [comment]
No worries! If you check out [DEVELOPMENT.md](https://github.com/kubecost/kubectl-cost/blob/main/DEVELOPMENT.md), you'll find an explanation for how the version info is filled. Someday I'd like to see if [go1.18's VCS info](https://tip.golang.org/doc/go1.18#debug/buildinfo) is enough to replace `govvv`, but I don't think that's the case right now.
