### ISSUE TITLE
Error: GLIBC not found

### ISSUE THREAD

**Issue by nickcurie** [kubecost/kubectl-cost#147]
Getting an error when running `kubectl cost` commands 

Commands Ran: `kubectl cost` and `kubectl cost namespace --show-all-resources`
Error Message: 
``/home/user/.krew/bin/kubectl-cost: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/user/.krew/bin/kubectl-cost)``
``/home/user/.krew/bin/kubectl-cost: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/user/.krew/bin/kubectl-cost)``
Environment: WSL2

**Comment by dwbrown2** [comment]
Any more repro steps you can share? cc @michaelmdresser

**Comment by michaelmdresser** [comment]
Reopening because we need a new release to fix this completely.

**Comment by dwbrown2** [comment]
@michaelmdresser I don't feel it's needed but no objection if you'd want to move forward with a patch!

**Comment by AjayTripathy** [comment]
Don't think we need to patch, let's just roll in 103
