### ISSUE TITLE
[FR/BUG] Show __idle__ costs (again) using OpenCost 

### ISSUE THREAD

**Issue by danielrolfes2307** [kubecost/kubectl-cost#163]
First-of-all I appreciate all the work that was done in this awesome tool :)

Imho it was possible for kubectl-cost  to show "idle"-costs for OpenCost in the past. This does not seem to work anymore.
I guess it is related to this: https://github.com/opencost/opencost/issues/1270#issuecomment-1818422930
It would be nice to add ?includeIdle=true parameter to the requests to opencost api (or make it an option).

Regards,
Daniel

**Comment by michaelmdresser** [comment]
Hi @danielrolfes2307, thank you for the suggestion. I have opened https://github.com/kubecost/kubectl-cost/pull/164 which should fix this. Once it is merged and a release has been cut, please give it a try.

**Comment by drolfes** [comment]
Awesome @michaelmdresser :)
Will give this a try (for sure) in the next days.

**Comment by michaelmdresser** [comment]
The release container this fix, `v0.6.1`, is now available. Please let me know if you encounter trouble, I do not test regularly against an Opencost environment so I'm reliant on your support.

**Comment by danielrolfes2307** [comment]
@michaelmdresser 
This works now. Thanks for the fix :)
![idle_costs](https://github.com/kubecost/kubectl-cost/assets/39588973/1d19f586-b904-441e-802b-735dcc9cb479)
