### ISSUE TITLE
OpenCost dependency is old

### ISSUE THREAD

**Issue by mattray** [kubecost/kubectl-cost#166]
https://github.com/kubecost/kubectl-cost/blob/main/go.mod#L9

I bring this up because 1.108 had a substantial refactor and we probably can't just bump up the version to the latest

**Comment by michaelmdresser** [comment]
Good point! kubectl-cost should only depend on `opencost/core`, so we'll have to update some imports but we'll likely benefit from a reduced dependency footprint.
