### ISSUE TITLE
Update used libraries to mitigate CVE scanners

### ISSUE THREAD

**Issue by lacunoc** [kubecost/kubectl-cost#167]
kubectl-cost is now constantly tested by our CVE scanners and has 2 HIGH and 1 CRITICAL marked issues.

Can you please upgrade:
`golang.org/x/net` from **v0.2.0** to **0.17.0** to fix _CVE-2022-41723_ and _CVE-2023-39325_

and also

`github.com/emicklei/go-restful` from **v2.9.5+incompatible** to **2.16.0** to fix _CVE-2022-1996_

Thanks in advance!

**Comment by michaelmdresser** [comment]
Thank you for the report @lacunoc! There is now a PR open to fix this. Once that is merged I will cut a new release.

**Comment by michaelmdresser** [comment]
The new release v0.6.2 has been cut. New binaries will be available via GitHub and Krew once the build workflows complete.
