### ISSUE TITLE
cost-model container is running and responding to the healthz endpoint, but the response is empty.

### ISSUE THREAD

**Issue by VenkySubbaraj** [kubecost/kubectl-cost#169]
The Kubecost cost-analyzer service is properly configured and exposing port 9003 for the cost-model container. The service is targeting the correct port (9003) and has an endpoint pointing to the cost-model container's IP (10.164.100.70:9003).
When you executed the curl command inside the cost-analyzer-frontend container to access the healthz endpoint of the cost-model container (http://localhost:9003/healthz), it returned an empty response. This indicates that the cost-model container is running and responding to the healthz endpoint, but the response is empty.

**Comment by michaelmdresser** [comment]
Hi @VenkySubbaraj, is this a problem with the `kubectl cost` CLI tool?

It sounds like you're reporting something unrelated, in which case I recommend reaching out via a GitHub issue on our Helm chart (https://github.com/kubecost/cost-analyzer-helm-chart/issues/new/choose) or in the Kubecost Slack.

**Comment by AjayTripathy** [comment]
As a note, /healthz is supposed to respond with a 200 and nothing else. What are you actually seeing in terms of data/ui?
