### ISSUE TITLE
Broken docs link....

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/kubectl-cost#170]
@bstuder99 there's a very important link that is broken here: https://docs.kubecost.com/install

Can you fix? What lessons can we learn from this?

cc @chipzoller @kwombach12

**Comment by dwbrown2** [comment]
The readme. What lessons can we learn from this? i.e. how many other broken links are out there and how can we address them?

**Comment by bstuder99** [comment]
Ahrefs has a feature called Broken Backlinks which identifies third party websites across the web linking towards the domain docs.kubecost.com, I've issued redirects where possible to mitigate near all of these. As for addressing content within public-facing Kubecost READMEs or other content, I can go through GitHub today and issue corrections where needed

**Comment by bstuder99** [comment]
This repo's README has had a single commit in the last year, so it sounds like the content does not need changes on a regular basis but is also not being maintained

**Comment by chipzoller** [comment]
Closed in #171
