### ISSUE TITLE
The Release v0.6.5 failed

### ISSUE THREAD

**Issue by suzuki-shunsuke** [kubecost/kubectl-cost#178]
https://github.com/kubecost/kubectl-cost/releases/tag/v0.6.5

<img width="301" alt="image" src="https://github.com/user-attachments/assets/13b2ca35-cb81-4f36-9f7f-9a95396bb867">

https://github.com/kubecost/kubectl-cost/actions/runs/11039467267/job/30665084505

<img width="757" alt="image" src="https://github.com/user-attachments/assets/fb41a9d0-f7b4-49b4-b119-f7d54391f1b3">

`Set up job` failed.

I think this issue would be solved by just retrying the workflow.

GitHub Actions Incident: https://www.githubstatus.com/incidents/1g9v7rry4z86

**Comment by suzuki-shunsuke** [comment]
v0.6.4 is same.

https://github.com/kubecost/kubectl-cost/releases/tag/v0.6.4

BTW, why is the latest version not v0.6.5 but v0.6.4?

<img width="159" alt="image" src="https://github.com/user-attachments/assets/0ea3fc96-085a-43c6-aa13-b11dff241cf2">

**Comment by cliffcolvin** [comment]
@suzuki-shunsuke thank you, we are working on this issue.

**Comment by cliffcolvin** [comment]
@suzuki-shunsuke please try v0.6.6 this should resolve the issue.

**Comment by suzuki-shunsuke** [comment]
Thank you! I confirmed the issue was resolved.
