### ISSUE TITLE
Shorthand for all cost categories

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/kubectl-cost#55]
I find my self running commands like 

```
kubectl cost namespace
```

getting results like 

```
+-------------------+--------------------+
| NAMESPACE         | MONTHLY RATE (ALL) |
+-------------------+--------------------+
| kube-system       |         171.735257 |
| kubecost-stage    |         148.139922 |
| kubecost          |         147.654236 |
| default           |         141.310171 |
| logging           |         138.559676 |
| frontend-services |         138.448290 |
| data-science      |         137.152641 |
+-------------------+--------------------+
| SUMMED            |        1023.000194 |
+-------------------+--------------------+
```

and then immediately want to understand what is driving the cost of each namespace. the `--show-all-resources` does exactly this, but I keep forgetting this flag name... what about a shorthand for this? one similar command flag would be `-o wide` or `--show-details` could work... just a couple ideas

**Comment by michaelmdresser** [comment]
Try `-A` (from `kubectl cost namespace --help`)

**Comment by dwbrown2** [comment]
Ohh, totally missed that! I like :)

Whats the guidance on lowercase vs uppercase?

**Comment by michaelmdresser** [comment]
I'm going to close this, feel free to re-open if you want to continue the discussion.
