### ISSUE TITLE
View cost by pod

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/kubectl-cost#63]
I know we originally had the ability to drill down to cost by pod (maybe even container). Any chance of bringing that back? I'd be interested to filter by namespace and then look at the cost of all pods in cases where there are many without a controller!

**Comment by michaelmdresser** [comment]
Definitely a good idea, I'll look into it.

**Comment by michaelmdresser** [comment]
Done in https://github.com/kubecost/kubectl-cost/pull/75
