### ISSUE TITLE
Add whitelist filters to commands

### ISSUE THREAD

**Issue by michaelmdresser** [kubecost/kubectl-cost#65]
We currently provide no way to filter output, something like `kubectl cost namespace --whitelist ns1,ns2,ns3` which would only display cost data for namespaces `ns1`, `ns2`, and `ns3`.

The backing `/aggregatedCostModel` API [provides filtering](https://github.com/kubecost/docs/blob/master/allocation-api.md#aggregated-cost-model-api) and [so does the `/allocation` API](https://github.com/kubecost/docs/blob/master/allocation.md#querying).

They do so in different ways, however, making this a little more complicated than just passing a filter through to the API call.

**Comment by michaelmdresser** [comment]
This should hold until https://github.com/kubecost/kubectl-cost/issues/90 is complete which will simplify this issue substantially.

**Comment by AdamStack18** [comment]
@michaelmdresser Closing out as #90 is complete.  Please reopen if needed.

**Comment by michaelmdresser** [comment]
Now that we have "v2 filters" I think we can just expose a standard filter string that gets passed to the backend!

Example usage: `kubectl cost namespace --filter 'container:"cost-model"'`

Filter language docs: https://github.com/kubecost/docs/blob/main/filters-api.md. Shouldn't be too necessary because the BE handles all parsing. Just pass the string to the `filter` query parameter.

**Comment by vladComan0** [comment]
I'd like to take a look on this if the issue is still relevant. Note that the filter language docs link does not work anymore.

**Comment by michaelmdresser** [comment]
This is certainly still relevant. The current docs link is https://docs.kubecost.com/apis/filters-api. It is my strong recommendation to "Just pass the string to the `filter` query parameter" because the backend APIs already implement the complex logic outlined in the documentation which is standardized in the product.
