### ISSUE TITLE
Efficiency is not displayed for the total column

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/kubectl-cost#79]
Running latest with the following command:

```
kubectl cost namespace --show-efficiency
``` 

and I get this output without efficiency metrics:

```
+-------------------+--------------------+
| NAMESPACE         | MONTHLY RATE (ALL) |
+-------------------+--------------------+
| kubecost          |          43.520037 |
| kube-system       |          34.135655 |
| kubecost-stage    |          25.915218 |
| default           |           3.467030 |
| frontend-services |           1.386221 |
| logging           |           1.341132 |
| data-science      |           0.009510 |
+-------------------+--------------------+
| SUMMED            |     USD 109.774804 |
+-------------------+--------------------+
```

**Comment by michaelmdresser** [comment]
In the current state, efficiency is not shown for the total cost column, only CPU and RAM. I worry that it is slightly misleading to show "total" efficiency when we don't calculate it for other resources. Happy to tag it onto the total column if you think that's fine.

**Comment by dwbrown2** [comment]
I think it's actually completely fine to show and reference documentation. 

Today, this measurement covers CPU + memory utilization, but we'll look to re-add disk utilization metrics (moved from cadvisor) and GPU utilization metrics (available in nvidia exporter)
