### ISSUE TITLE
Stop using /aggregatedCostModel

### ISSUE THREAD

**Issue by michaelmdresser** [kubecost/kubectl-cost#90]
Kubectl cost [uses](https://github.com/kubecost/kubectl-cost/blob/main/pkg/query/aggapi.go#L37) the [Aggregated cost model API](https://github.com/kubecost/docs/blob/master/allocation-api.md#aggregated-cost-model-api) for monthly rate queries, i.e. non `--historical` queries. That API is old and we want to switch everything to use the [Allocation API](https://github.com/kubecost/docs/blob/master/allocation.md) which `kubectl cost` [already uses](https://github.com/kubecost/kubectl-cost/blob/main/pkg/query/allocation.go#L90) for `--historical` queries.

We should be able to cut out `/aggregatedCostModel` queries by hitting `/allocation` and then transforming the cost numbers to a monthly rate based on the coverage of the resulting data. Special care will have to be taken due to the time-based quirks of the Allocation API. Instead of doing something like `cost * (month / query window)` we should do `cost * (month / duration of resulting data coverage)`.

**Comment by nikovacevic** [comment]
Each allocation comes with a `mintues` field, so it should be possible to scale to monthly rate based on active time or window time. (There are still caveats, like `CronJob`-based allocations, allocated by controller and accumulated over a long window, where the `mintues` field will count as the time between the start of the first run and the end of the last run.)

**Comment by michaelmdresser** [comment]
Resolved by #93
