### ISSUE TITLE
Kubecost incorrectly calculates savings

### ISSUE THREAD

**Issue by MarkSRobinson** [kubecost/kubectl-cost#96]
On the overview page, it reports my cluster as costing $42k/mo, but on /request-sizing.html it is reporting $225k/mo in potential savings when the window is 30 days and the profile is High Availability.

I think you're multiplying possible savings over a month by the number of days in the look-back window.

**Comment by dwbrown2** [comment]
Hi Mark, would you be able to share what kubecost version? This sounds like you are hitting a new issue that was just addressed in our release candidate from last week -- https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.82.0-rc.0

**Comment by MarkSRobinson** [comment]
@dwbrown2 `gcr.io/kubecost1/cost-model:prod-1.81.0`

**Comment by dwbrown2** [comment]
This should be addressed in our two latest RC builds. You can grab these with this process: https://github.com/kubecost/docs/blob/master/release-process.md#release-candidate-rc-builds

Alternatively, these should be coming to production next week!

**Comment by michaelmdresser** [comment]
Hi @MarkSRobinson, are you still having this problem?

**Comment by MarkSRobinson** [comment]
I haven't upgraded to check if it's resolved.  So let's close this issue and I'll open a new ticket if it persists when I eventually upgrade.
